[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalculatordapp = "1fCp2GoCozftVb2w4HyGhbocHK1fxcFtadytPtEJ23J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/oxray/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
